version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Downloading reference code from S3"
      - aws s3 sync s3://testscripts-geetha /tmp/chatgpt
      - echo "Running token-based similarity check"
      - python3 compare_code.py file1.py /tmp/chatgpt/geetha.txt

